version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      security-patches:
        applies-to: security-updates
        patterns:
          - "*"
      prod-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
